### PR TITLE
week 1

### PR DESCRIPTION
**Pull request by marcellourbani**

### CODE REVIEW

**Comment by nicogeburek** [comment]
Hi @marcellourbani, looks like we hadn't fixed the issue with `package-lock.json`, but hopefully we did so [now](https://github.com/SAP-samples/sap-community-code-challenge-ui5/commit/d6f4b7b5b26574040bc4b17eec59f541c26564c8). Your app looks fine, so I would consider it as a successful entry for the first week, even tough we didn't get the GitHub action to pass (our bad, not yours). You can either update your PR if you want or just wait until Wednesday, when we will add a new test to the project.

**Comment by marcellourbani** [comment]
Thank you
BTW, I can't run the tests from within the devcontainer.
I mostly got it to work but not quite.

If I have time to fix it will send a PR

Marcello

**Comment by nicogeburek** [comment]
Hi @marcellourbani, as already discussed in a [parallel thread](https://github.com/SAP-samples/sap-community-code-challenge-ui5/commit/046cdb8aae34d8d69a129d60cbd345fec40c79fb), we have found and fixed the real issue that was causing the action to fail. Fetching the upstream for your forked repo should update this PR and make the action pass.

**Review by nicogeburek — APPROVED** [review]

**Comment by marcellourbani** [comment]
done. Don't think I have time for another today though

**Comment by marcellourbani** [comment]
can you please delete this? I made a mess...

**Comment by nicogeburek** [comment]
Unfortunately you can only close pull request, but you can delete them. You can delete your forked repo however.

**Comment by nicogeburek** [comment]
I can see why you want this PR to be removed, I contacted GitHub Support to have it removed. Will keep you updated.

**Pull request closed without merging**
