### PR TITLE
Passing tests of weeks 1, 2, 3 and 4

### PR DESCRIPTION
**Pull request by whydrae**
I have to create a new pull request, because I broke my repository. Previous pull request: https://github.com/SAP-samples/sap-community-code-challenge-ui5/pull/16.

@nicogeburek, which version of npm you are using? I think we have conflicts with `package-lock.json`, because I'm using a newer one.

### CODE REVIEW

**Review by nicoschoenteich — APPROVED** [review]

**Comment by nicogeburek** [comment]
Hi @whydrae,
Good job, thanks for taking part and submitting a new PR.
I used npm version 6.14.14. I wouldn't worry about the conflicts too much for now, as the wdi5 tests are passing 😉

**Comment by nicogeburek** [comment]
Good job!

**Comment by nicogeburek** [comment]
Hi @whydrae, interesting observation. Might be something worth [reporting](https://github.com/js-soft/wdi5/issues).

**Comment by nicogeburek** [comment]
Good job! Thanks for participating 🙌

**Comment by nicogeburek** [comment]
Thanks a lot for fixing the await issue 🙌🏻

**Pull request closed without merging**
